### ISSUE TITLE
Can't find the npz file in the hSMAL model

### ISSUE THREAD

**Issue by YogerChen** [Celiali/PFERD#1]
Hi, this dataset is fascinating! While I'm trying to run the Projection.py script, I don't seem to find the [hSMAL](https://sites.google.com/view/cv4horses/cv4horses) model npz file "my_smpl_0000_horse_new_skeleton_horse.npz" in the google drive link provided, which is required in the config. Could you please specify where to find this file or any other ways to get it? Thanks!

**Comment by Celiali** [comment]
Hi, thank you for your interest. The file is added to the google drive link.

**Comment by YogerChen** [comment]
I can find it now. Thank you!
